# Generated by Django 5.2.17 on 2026-09-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0002_alter_proyectomodels_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectomodels',
            name='responsable',
            field=models.CharField(default='Sin responsable', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectomodels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
